import { useState, useEffect } from 'react';
import type { ChangeEvent } from 'react';
import { 
  BookOpen, 
  Sparkles, 
  Wand2, 
  RefreshCw, 
  Key, 
  Download, 
  ArrowLeft, 
  ArrowRight, 
  Trash2, 
  Edit2, 
  Check, 
  Plus, 
  FileText, 
  HelpCircle,
  AlertCircle
} from 'lucide-react';
import { generateStory, generateImage } from './gemini';
import type { StoryConfig, StoryPage, GeneratedBook } from './gemini';
import { saveBookDB, getBooksDB, deleteBookDB } from './db';

interface BookWithMetadata extends GeneratedBook {
  id: string;
  createdAt: string;
  config: StoryConfig;
  seeds: number[]; // seeds for each page to persist images
  images?: string[]; // base64 images generated by Gemini
  timestamp?: number; // timestamp for sorting
}

const THEME_OPTIONS = [
  { id: 'Fantasy', label: '奇幻 🪄', icon: '🪄', promptStyle: 'magical watercolor illustration, children\'s book art, soft lighting, vibrant colors' },
  { id: 'Sci-Fi', label: '科幻 🚀', icon: '🚀', promptStyle: 'dreamy retro-futuristic digital painting, soft glow, children\'s sci-fi illustration' },
  { id: 'Mystery', label: '解謎 🕵️‍♂️', icon: '🕵️‍♂️', promptStyle: 'cozy mystery watercolor, warm candlelight, detailed children\'s book illustration' },
  { id: 'Fairy Tale', label: '童話 🏰', icon: '🏰', promptStyle: 'enchanted storybook illustration, gold leaf details, whimsical pastel colors' },
  { id: 'Custom', label: '自訂 🎨', icon: '🎨', promptStyle: 'beautiful digital children\'s illustration' },
];

export default function App() {
  // API Key State
  const [apiKey, setApiKey] = useState<string>('');
  const [showKeyModal, setShowKeyModal] = useState<boolean>(false);
  const [tempKey, setTempKey] = useState<string>('');
  const [bookToDelete, setBookToDelete] = useState<BookWithMetadata | null>(null);
  const [serverHasKey, setServerHasKey] = useState<boolean>(false);

  // Setup Wizard State
  const [theme, setTheme] = useState<string>('Fantasy');
  const [customStyle, setCustomStyle] = useState<string>('');
  const [protagonistName, setProtagonistName] = useState<string>('里歐');
  const [protagonistDescription, setProtagonistDescription] = useState<string>('一隻勇敢的小獅子，有蓬鬆的金色鬃毛和綠色眼睛');
  const [companionName, setCompanionName] = useState<string>('皮皮');
  const [companionDescription, setCompanionDescription] = useState<string>('一隻總是背著閃亮星塵小包包的藍色小鳥');
  const [specialTool, setSpecialTool] = useState<string>('一盞會發光的星星提燈');
  const [pagesCount, setPagesCount] = useState<number>(5);
  const [tone, setTone] = useState<string>('Whimsical');
  const [ageGroup, setAgeGroup] = useState<string>('6-8 years');
  const [model, setModel] = useState<string>('gemini-2.5-flash');
  const [illustrationStyle, setIllustrationStyle] = useState<'fairy' | 'simple_strokes'>('fairy');

  // App States
  const [loading, setLoading] = useState<boolean>(false);
  const [loadingStep, setLoadingStep] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  
  // Library and Current Book States
  const [library, setLibrary] = useState<BookWithMetadata[]>([]);
  const [currentBook, setCurrentBook] = useState<BookWithMetadata | null>(null);
  const [currentPageIndex, setCurrentPageIndex] = useState<number>(0);
  
  // Image states
  const [imageLoading, setImageLoading] = useState<boolean>(false);
  const [imageError, setImageError] = useState<boolean>(false);
  
  // Editor States
  const [isEditing, setIsEditing] = useState<boolean>(false);
  const [editedText, setEditedText] = useState<string>('');
  const [editedPrompt, setEditedPrompt] = useState<string>('');

  // Cross-device sync states
  const syncKey = 'verify-mcp-sync-keyverify-mcp-sync-key';
  const [syncStatus, setSyncStatus] = useState<'idle' | 'syncing' | 'error'>('idle');
  const [syncError, setSyncError] = useState<string | null>(null);

  const readSyncResponse = async (response: Response) => {
    const contentType = response.headers.get('content-type') || '';
    const text = await response.text();
    let data: any = null;

    if (contentType.includes('application/json')) {
      try {
        data = text ? JSON.parse(text) : null;
      } catch {
        throw new Error('雲端書庫資料格式無法解析，請稍後再試。');
      }
    }

    if (!response.ok) {
      throw new Error(data?.error || data?.message || `雲端書庫同步失敗（HTTP ${response.status}）`);
    }

    if (!contentType.includes('application/json')) {
      throw new Error('雲端書庫暫時回傳非 JSON 資料，請稍後再試。');
    }

    return data;
  };

  // Merge two library lists (resolving duplicate IDs by timestamp)
  const mergeLibraries = (local: BookWithMetadata[], remote: BookWithMetadata[]): BookWithMetadata[] => {
    const mergedMap = new Map<string, BookWithMetadata>();

    // Add all local books first
    for (const book of local) {
      mergedMap.set(book.id, book);
    }

    // Merge remote books
    for (const book of remote) {
      const existing = mergedMap.get(book.id);
      if (!existing) {
        mergedMap.set(book.id, book);
      } else {
        const localTime = existing.timestamp || 0;
        const remoteTime = book.timestamp || 0;
        if (remoteTime > localTime) {
          mergedMap.set(book.id, book);
        }
      }
    }

    const mergedList = Array.from(mergedMap.values());
    mergedList.sort((a, b) => (b.timestamp || 0) - (a.timestamp || 0));
    return mergedList;
  };

  // Push library to sync server
  const pushLibraryToCloud = async (key: string, books: BookWithMetadata[]) => {
    if (!key) return;
    try {
      const response = await fetch('/api/sync', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ key, books })
      });
      const data = await readSyncResponse(response);
      if (data.error === 'KV_NOT_BOUND') {
        setSyncStatus('error');
        setSyncError("尚未設定 Cloudflare KV 資料庫。請在 Cloudflare 專案的 Settings > Functions > KV namespace bindings 綁定名為 'LIBRARY_KV' 的 KV 命名空間，才能啟用同步。");
      }
    } catch (e: any) {
      console.error('Failed to push library to sync server:', e);
      setSyncStatus('error');
      setSyncError(e.message || '同步書庫時發生網路錯誤');
    }
  };

  // Synchronize local library with KV storage
  const syncLibrary = async (key: string) => {
    if (!key) return;
    setSyncStatus('syncing');
    setSyncError(null);
    try {
      const response = await fetch(`/api/sync?key=${encodeURIComponent(key)}`);
      const remoteBooks = await readSyncResponse(response);
      
      if (remoteBooks && remoteBooks.error === 'KV_NOT_BOUND') {
        setSyncStatus('error');
        setSyncError("尚未設定 Cloudflare KV 資料庫。請在 Cloudflare 專案的 Settings > Functions > KV namespace bindings 綁定名為 'LIBRARY_KV' 的 KV 命名空間，才能啟用同步。");
        return;
      }

      if (Array.isArray(remoteBooks)) {
        const localBooks = await getBooksDB();
        const mergedBooks = mergeLibraries(localBooks, remoteBooks);
        
        // Save all merged books to IndexedDB
        for (const book of mergedBooks) {
          await saveBookDB(book);
        }
        
        setLibrary(mergedBooks);
        
        // Push merged database back to cloud
        await pushLibraryToCloud(key, mergedBooks);
        setSyncStatus('idle');
      } else {
        throw new Error('收到的同步資料格式無效');
      }
    } catch (e: any) {
      console.error('Sync failed:', e);
      setSyncStatus('error');
      setSyncError(e.message || '同步失敗，可能是網路或伺服器問題。');
    }
  };

  // Trigger sync on load or when sync key is changed
  useEffect(() => {
    if (syncKey) {
      syncLibrary(syncKey);
    }
  }, [syncKey]);

  // Load API Key & Library on startup
  useEffect(() => {
    const savedKey = localStorage.getItem('gemini_api_key');
    if (savedKey) {
      setApiKey(savedKey);
      setTempKey(savedKey);
    }

    // Check server key configuration
    fetch('/api/config')
      .then(res => res.json())
      .then((data: any) => {
        setServerHasKey(data.hasKey);
        if (!data.hasKey && !savedKey) {
          setShowKeyModal(true);
        }
      })
      .catch(err => {
        console.error('Failed to fetch server config:', err);
        if (!savedKey) {
          setShowKeyModal(true);
        }
      });

    const loadLibrary = async () => {
      try {
        let books = await getBooksDB();
        
        // Migration from localStorage if needed
        const savedBooks = localStorage.getItem('adventure_books');
        if (savedBooks && books.length === 0) {
          const parsed = JSON.parse(savedBooks);
          if (Array.isArray(parsed) && parsed.length > 0) {
            for (const b of parsed) {
              await saveBookDB({
                ...b,
                timestamp: b.timestamp || Date.now()
              });
            }
            books = await getBooksDB();
            localStorage.removeItem('adventure_books');
          }
        }
        
        // Sort books by timestamp desc (newest first)
        books.sort((a, b) => (b.timestamp || 0) - (a.timestamp || 0));
        setLibrary(books);
      } catch (e) {
        console.error('Failed to load books database', e);
      }
    };
    loadLibrary();
  }, []);

  // Reset image error state on page change
  useEffect(() => {
    setImageError(false);
  }, [currentPageIndex, currentBook?.id]);

  // Save key
  const handleSaveKey = (key: string) => {
    const trimmed = key.trim();
    localStorage.setItem('gemini_api_key', trimmed);
    setApiKey(trimmed);
    setShowKeyModal(false);
  };

  // Clear key
  const handleClearKey = () => {
    localStorage.removeItem('gemini_api_key');
    setApiKey('');
    setTempKey('');
    setShowKeyModal(true);
  };

  // Generate Book Action
  const handleGenerateBook = async () => {
    if (!apiKey && !serverHasKey) {
      setShowKeyModal(true);
      return;
    }

    setLoading(true);
    setError(null);
    setLoadingStep('正在聯絡魔法書記官（連線到 Gemini）...');

    const config: StoryConfig = {
      theme,
      protagonistName,
      protagonistDescription,
      companionName: companionName ? companionName : undefined,
      companionDescription: companionDescription ? companionDescription : undefined,
      specialTool: specialTool ? specialTool : undefined,
      pagesCount,
      tone,
      ageGroup,
      illustrationStyle
    };

    try {
      setLoadingStep('正在撰寫冒險藍圖...');
      const responseBook = await generateStory(apiKey, config, model);

      // Generate random seed for each page
      const seeds = Array.from({ length: responseBook.pages.length }, () => 
        Math.floor(Math.random() * 1000000)
      );

      const selectedTheme = THEME_OPTIONS.find(t => t.id === theme);
      const styleSuffix = illustrationStyle === 'simple_strokes'
        ? 'minimalist simple black ink outline sketch on a clean solid white background, cute childlike marker doodle style, simple strokes, black ink on white paper, no color, no background detail'
        : (selectedTheme ? selectedTheme.promptStyle : (customStyle || 'children\'s book illustration'));

      const images: string[] = [];
      for (let i = 0; i < responseBook.pages.length; i++) {
        setLoadingStep(`正在繪製第 ${i + 1} / ${responseBook.pages.length} 頁插圖...`);
        const page = responseBook.pages[i];
        try {
          const imgData = await generateImage(apiKey, `${page.illustrationPrompt}, ${styleSuffix}`);
          images.push(imgData);
        } catch (e: any) {
          console.error(`Failed to generate image for page ${i + 1}`, e);
          images.push('');
        }
      }

      const newBook: BookWithMetadata = {
        ...responseBook,
        id: crypto.randomUUID ? crypto.randomUUID() : Math.random().toString(36).substring(2, 9),
        createdAt: new Date().toLocaleDateString(),
        config,
        seeds,
        images,
        timestamp: Date.now()
      };

      // Save to library DB
      await saveBookDB(newBook);
      const updatedLibrary = [newBook, ...library];
      setLibrary(updatedLibrary);
      if (syncKey) {
        await pushLibraryToCloud(syncKey, updatedLibrary);
      }

      // Display the book
      setCurrentBook(newBook);
      setCurrentPageIndex(0);
    } catch (err: any) {
      console.error(err);
      setError(err.message || '發生未預期的錯誤。請確認 API Key 與網路連線。');
    } finally {
      setLoading(false);
    }
  };

  // Re-roll image seed (regenerate illustration)
  const handleRerollImage = async () => {
    if (!currentBook) return;

    const selectedTheme = THEME_OPTIONS.find(t => t.id === currentBook.config.theme);
    const styleSuffix = currentBook.config.illustrationStyle === 'simple_strokes'
      ? 'minimalist simple black ink outline sketch on a clean solid white background, cute childlike marker doodle style, simple strokes, black ink on white paper, no color, no background detail'
      : (selectedTheme ? selectedTheme.promptStyle : (customStyle || 'children\'s book illustration'));

    if (!apiKey && !serverHasKey) {
      setShowKeyModal(true);
      return;
    }
    setImageLoading(true);
    try {
      const page = currentBook.pages[currentPageIndex];
      const newImgData = await generateImage(apiKey, `${page.illustrationPrompt}, ${styleSuffix}`);

      const updatedImages = currentBook.images ? [...currentBook.images] : Array(currentBook.pages.length).fill('');
      updatedImages[currentPageIndex] = newImgData;

      const updatedBook = {
        ...currentBook,
        images: updatedImages
      };

      await updateBookInLibrary(updatedBook);
    } catch (e: any) {
      console.error(e);
      alert(e.message || '無法使用 Gemini 重新生成插圖。');
    } finally {
      setImageLoading(false);
    }
  };

  // Update book in library and current state
  const updateBookInLibrary = async (updatedBook: BookWithMetadata) => {
    setCurrentBook(updatedBook);
    try {
      await saveBookDB(updatedBook);
      const updatedLibrary = library.map(b => b.id === updatedBook.id ? updatedBook : b);
      setLibrary(updatedLibrary);
      if (syncKey) {
        await pushLibraryToCloud(syncKey, updatedLibrary);
      }
    } catch (e) {
      console.error('Failed to update book', e);
    }
  };

  // Save manual edits to text or prompts
  const handleSaveChanges = async () => {
    if (!currentBook) return;
    const updatedPages = [...currentBook.pages];
    updatedPages[currentPageIndex] = {
      ...updatedPages[currentPageIndex],
      storyText: editedText,
      illustrationPrompt: editedPrompt
    };

    const updatedBook = {
      ...currentBook,
      pages: updatedPages
    };

    await updateBookInLibrary(updatedBook);
    setIsEditing(false);
  };

  // Enter editing mode
  const startEditing = () => {
    if (!currentBook) return;
    const currentPage = currentBook.pages[currentPageIndex];
    setEditedText(currentPage.storyText);
    setEditedPrompt(currentPage.illustrationPrompt);
    setIsEditing(true);
  };

  // Delete Book
  const handleDeleteBook = async (id: string) => {
    try {
      await deleteBookDB(id);
      const updatedLibrary = library.filter(b => b.id !== id);
      setLibrary(updatedLibrary);
      if (syncKey) {
        await pushLibraryToCloud(syncKey, updatedLibrary);
      }
      if (currentBook?.id === id) {
        setCurrentBook(null);
      }
    } catch (e: any) {
      console.error('Failed to delete book', e);
      alert('刪除書本失敗：' + (e.message || e));
    }
  };

  // Export Book to HTML File
  const handleExportHtml = () => {
    if (!currentBook) return;

    const bookPagesHtml = currentBook.pages.map((page, idx) => {
      const selectedTheme = THEME_OPTIONS.find(t => t.id === currentBook.config.theme);
      const styleSuffix = selectedTheme ? selectedTheme.promptStyle : 'children\'s book illustration';
      const imageUrl = currentBook.images && currentBook.images[idx]
        ? currentBook.images[idx]
        : `https://image.pollinations.ai/prompt/${encodeURIComponent(page.illustrationPrompt + ', ' + styleSuffix)}?width=800&height=600&nologo=true&seed=${currentBook.seeds[idx]}`;

      return `
        <div class="page-container">
          <div class="book-card">
            <div class="image-side">
              <img src="${imageUrl}" alt="第 ${idx + 1} 頁插圖" />
            </div>
            <div class="text-side">
              <div class="story-content">${page.storyText}</div>
              <div class="page-footer">第 ${idx + 1} 頁</div>
            </div>
          </div>
        </div>
      `;
    }).join('');

    const htmlContent = `
      <!DOCTYPE html>
      <html lang="zh-Hant">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${currentBook.title} - 冒險故事書</title>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;600&family=Noto+Serif+TC:wght@400;600;700&display=swap" rel="stylesheet">
        <style>
          body {
            background-color: #0c0f1d;
            font-family: 'Noto Sans TC', sans-serif;
            color: #f8fafc;
            margin: 0;
            padding: 40px 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
          }
          h1 {
            font-family: 'Noto Serif TC', serif;
            font-size: 3rem;
            text-align: center;
            margin-bottom: 40px;
            background: linear-gradient(135deg, #f8fafc 30%, #a5b4fc 70%, #ec4899 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
          }
          .page-container {
            width: 100%;
            max-width: 1000px;
            margin-bottom: 60px;
            page-break-after: always;
          }
          .book-card {
            display: grid;
            grid-template-columns: 1.2fr 1fr;
            background: #fdfbf7;
            border-radius: 16px;
            overflow: hidden;
            box-shadow: 0 20px 40px rgba(0,0,0,0.5);
            border: 6px solid #3e2723;
            color: #2d2a26;
            min-height: 500px;
          }
          @media (max-width: 768px) {
            .book-card {
              grid-template-columns: 1fr;
            }
          }
          .image-side {
            background-color: #e2e8f0;
            display: flex;
            align-items: center;
            justify-content: center;
          }
          .image-side img {
            width: 100%;
            height: 100%;
            object-fit: cover;
            display: block;
          }
          .text-side {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            padding: 40px;
            background: linear-gradient(to right, #f7f3eb 0%, #fdfbf7 8%, #fdfbf7 100%);
          }
          .story-content {
            font-family: 'Noto Serif TC', serif;
            font-size: 1.4rem;
            line-height: 1.7;
            color: #3a3530;
          }
          .page-footer {
            font-family: 'Noto Serif TC', serif;
            font-style: italic;
            font-size: 1rem;
            color: #8b8070;
            text-align: center;
            margin-top: 20px;
            border-top: 1px dashed rgba(0,0,0,0.1);
            padding-top: 10px;
          }
          .no-print-header {
            margin-bottom: 20px;
            display: flex;
            gap: 10px;
          }
          button {
            background: #6366f1;
            border: none;
            color: white;
            padding: 10px 20px;
            font-weight: 600;
            border-radius: 6px;
            cursor: pointer;
          }
          @media print {
            body { background: #fff !important; color: #000; padding: 0; }
            .no-print-header { display: none !important; }
            .book-card { box-shadow: none !important; border: none !important; }
          }
        </style>
      </head>
      <body>
        <div class="no-print-header">
          <button onclick="window.print()">列印成 PDF</button>
        </div>
        <h1>${currentBook.title}</h1>
        ${bookPagesHtml}
      </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${currentBook.title.replace(/\s+/g, '_')}_adventure.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Export entire library to JSON file
  const handleExportLibraryJSON = () => {
    if (library.length === 0) {
      alert("書庫目前沒有可匯出的故事書。");
      return;
    }
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(library, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `adventure_forge_library_${new Date().toISOString().slice(0, 10)}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    document.body.removeChild(downloadAnchor);
  };

  // Import library from JSON file
  const handleImportLibraryJSON = (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const imported = JSON.parse(e.target?.result as string);
        if (!Array.isArray(imported)) {
          throw new Error("匯入的檔案不是有效的書庫陣列。");
        }
        
        setLoading(true);
        setLoadingStep("正在將故事匯入書庫...");
        
        let count = 0;
        for (const book of imported) {
          if (book.title && book.pages && book.config) {
            // Verify if book already exists in library to avoid duplication
            if (!library.some(b => b.id === book.id)) {
              await saveBookDB(book);
              count++;
            }
          }
        }
        
        // Reload library from IndexedDB
        const updated = await getBooksDB();
        setLibrary(updated);
        if (syncKey) {
          await pushLibraryToCloud(syncKey, updated);
        }
        
        alert(`成功匯入 ${count} 本新故事書到書庫！`);
      } catch (err: any) {
        console.error(err);
        alert("匯入書庫失敗：" + err.message);
      } finally {
        setLoading(false);
      }
    };
    reader.readAsText(file);
  };

  // Get current page illustration image URL
  const getImageUrl = (page: StoryPage, idx: number) => {
    if (!currentBook) return '';
    if (currentBook.images && currentBook.images[idx]) {
      return currentBook.images[idx];
    }
    const selectedTheme = THEME_OPTIONS.find(t => t.id === currentBook.config.theme);
    const styleSuffix = currentBook.config.illustrationStyle === 'simple_strokes'
      ? 'minimalist simple black ink outline sketch on a clean solid white background, cute childlike marker doodle style, simple strokes, black ink on white paper, no color, no background detail'
      : (selectedTheme ? selectedTheme.promptStyle : (customStyle || 'children\'s book illustration'));
    
    return `https://image.pollinations.ai/prompt/${encodeURIComponent(page.illustrationPrompt + ', ' + styleSuffix)}?width=700&height=600&nologo=true&seed=${currentBook.seeds[idx]}`;
  };

  return (
    <div className="container">
      {/* App Header */}
      <header className="app-header no-print">
        <div className="app-title-container">
          <BookOpen className="app-title-icon" size={64} />
          <span className="app-logo text-gradient">胡說亂畫</span>
        </div>
        
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <button 
            className="btn btn-secondary" 
            onClick={() => {
              if (apiKey) {
                handleClearKey();
              } else {
                setShowKeyModal(true);
              }
            }}
            title={apiKey ? "清除 Gemini API Key" : (serverHasKey ? "設定自訂 API Key" : "設定 Gemini API Key")}
            style={{ padding: '8px 16px', fontSize: '0.9rem' }}
          >
            <Key size={16} />
            {apiKey ? '清除自訂 Key' : (serverHasKey ? '使用自訂 Key' : '設定 API Key')}
          </button>
          
          {currentBook && (
            <button 
              className="btn btn-primary" 
              onClick={() => setCurrentBook(null)}
              style={{ padding: '8px 16px', fontSize: '0.9rem' }}
            >
              <Plus size={16} />
              新故事書
            </button>
          )}
        </div>
      </header>

      {/* Main Content Area */}
      <main>
        {/* Loading Spinner */}
        {loading && (
          <div className="glass-panel" style={{ padding: '60px 40px', textAlign: 'center', margin: '40px auto', maxWidth: '600px' }}>
            <div style={{ position: 'relative', width: '80px', height: '80px', margin: '0 auto 24px' }}>
              <div style={{
                boxSizing: 'border-box',
                display: 'block',
                position: 'absolute',
                width: '64px',
                height: '64px',
                margin: '8px',
                border: '8px solid var(--primary)',
                borderRadius: '50%',
                animation: 'loading-spin 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite',
                borderColor: 'var(--primary) transparent transparent transparent'
              }}></div>
            </div>
            <h3 style={{ fontSize: '1.4rem', marginBottom: '12px' }}>正在編織魔法...</h3>
            <p style={{ color: 'var(--text-secondary)' }}>{loadingStep}</p>
            <style>{`
              @keyframes loading-spin {
                0% { transform: rotate(0deg); }
                100% { transform: rotate(360deg); }
              }
            `}</style>
          </div>
        )}

        {/* Error Alert */}
        {error && !loading && (
          <div className="glass-panel" style={{ padding: '24px', borderColor: '#ef4444', backgroundColor: 'rgba(239, 68, 68, 0.08)', margin: '20px 0', display: 'flex', gap: '16px', alignItems: 'center' }}>
            <AlertCircle size={28} style={{ color: '#ef4444', flexShrink: 0 }} />
            <div>
              <h4 style={{ color: '#ef4444', fontWeight: 600, marginBottom: '4px' }}>魔法出錯了</h4>
              <p style={{ fontSize: '0.95rem', color: 'var(--text-primary)' }}>{error}</p>
            </div>
          </div>
        )}

        {/* BOOK READER VIEW */}
        {currentBook && !loading && (
          <div>
            <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
              <button 
                className="btn btn-secondary" 
                onClick={() => setCurrentBook(null)}
              >
                <ArrowLeft size={16} />
                返回書庫
              </button>
              <div style={{ display: 'flex', gap: '12px' }}>
                <button className="btn btn-secondary" onClick={handleExportHtml}>
                  <Download size={16} />
                  匯出 HTML
                </button>
                <button className="btn btn-accent" onClick={() => window.print()}>
                  <FileText size={16} />
                  列印 PDF
                </button>
              </div>
            </div>

            {/* Title Display */}
            <h2 className="text-gradient" style={{ textAlign: 'center', fontSize: '2.5rem', fontFamily: 'var(--font-book)', marginBottom: '32px' }}>
              {currentBook.title}
            </h2>

            {/* The Actual Book Page Layout */}
            <div className="book-layout">
              {/* Illustration Side */}
              <div className="book-image-side">
                {imageLoading && (
                  <div className="skeleton" style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 2 }}></div>
                )}
                <img 
                  src={imageError 
                    ? `https://robohash.org/${encodeURIComponent(currentBook.pages[currentPageIndex].illustrationPrompt)}?set=set4`
                    : getImageUrl(currentBook.pages[currentPageIndex], currentPageIndex)
                  } 
                  alt={`第 ${currentPageIndex + 1} 頁插圖`}
                  className="book-image"
                  onLoadStart={() => setImageLoading(true)}
                  onLoad={() => setImageLoading(false)}
                  onError={() => {
                    console.warn("Primary image failed to load, falling back to Robohash");
                    setImageError(true);
                    setImageLoading(false);
                  }}
                />
              </div>

              {/* Text Side */}
              <div className="book-text-side">
                <p className="book-story-text">
                  {currentBook.pages[currentPageIndex].storyText}
                </p>
                
                <div>
                  {/* Page Footer / Number */}
                  <div className="book-page-number">
                    第 {currentPageIndex + 1} / {currentBook.pages.length} 頁
                  </div>
                </div>
              </div>
            </div>

            {/* Navigation & Controls */}
            <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '24px' }}>
              <button 
                className="btn btn-secondary"
                disabled={currentPageIndex === 0}
                onClick={() => {
                  setCurrentPageIndex(currentPageIndex - 1);
                  setIsEditing(false);
                }}
              >
                <ArrowLeft size={16} />
                上一頁
              </button>
              
              <div style={{ display: 'flex', gap: '12px' }}>
                <button 
                  className="btn btn-secondary"
                  onClick={handleRerollImage}
                  title="為這頁插圖生成新的版本"
                >
                  <RefreshCw size={16} />
                  重抽插圖
                </button>
                <button 
                  className="btn btn-secondary"
                  onClick={isEditing ? handleSaveChanges : startEditing}
                >
                  {isEditing ? <Check size={16} /> : <Edit2 size={16} />}
                  {isEditing ? '儲存變更' : '編輯頁面'}
                </button>
              </div>

              <button 
                className="btn btn-secondary"
                disabled={currentPageIndex === currentBook.pages.length - 1}
                onClick={() => {
                  setCurrentPageIndex(currentPageIndex + 1);
                  setIsEditing(false);
                }}
              >
                下一頁
                <ArrowRight size={16} />
              </button>
            </div>

            {/* Editor Workspace Panel (Grows/Shrinks when open) */}
            {isEditing && (
              <div className="glass-panel editor-panel no-print" style={{ marginTop: '30px' }}>
                <h3 style={{ fontSize: '1.2rem', color: 'var(--primary)' }}>冒險工作室編輯器</h3>
                
                <div className="form-group">
                  <label className="form-label">故事文字</label>
                  <textarea 
                    className="form-textarea"
                    value={editedText}
                    onChange={(e) => setEditedText(e.target.value)}
                    style={{ minHeight: '120px' }}
                  />
                </div>

                <div className="form-group">
                  <label className="form-label">插圖提示詞（AI 描述）</label>
                  <textarea 
                    className="form-textarea"
                    value={editedPrompt}
                    onChange={(e) => setEditedPrompt(e.target.value)}
                    style={{ minHeight: '100px' }}
                  />
                  <small style={{ color: 'var(--text-muted)' }}>
                    提示：讓主角外觀描述保持一致，插圖風格會更連貫。
                  </small>
                </div>

                <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginTop: '8px' }}>
                  <button className="btn btn-secondary" onClick={() => setIsEditing(false)}>取消</button>
                  <button className="btn btn-primary" onClick={handleSaveChanges}>套用變更</button>
                </div>
              </div>
            )}
          </div>
        )}

        {/* SETUP WIZARD & LIBRARY DASHBOARD */}
        {!currentBook && !loading && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '40px' }}>
            
            {/* The Setup Panel */}
            <div className="glass-panel" style={{ padding: '32px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '24px', borderBottom: '1px solid var(--border-glass)', paddingBottom: '16px' }}>
                <Wand2 size={24} style={{ color: 'var(--accent)' }} />
                <h2 style={{ fontSize: '1.8rem', fontWeight: 600 }}>說個大家都不相信的故事吧</h2>
              </div>

              <div className="wizard-grid">
                
                {/* Left Form: Theme & Protagonist */}
                <div>
                  <div className="form-group">
                    <label className="form-label">選擇冒險主題</label>
                    <div className="theme-grid">
                      {THEME_OPTIONS.map((t) => (
                        <div 
                          key={t.id} 
                          className={`theme-card ${theme === t.id ? 'active' : ''}`}
                          onClick={() => setTheme(t.id)}
                        >
                          <div style={{ fontSize: '1.8rem', marginBottom: '6px' }}>{t.icon}</div>
                          <div style={{ fontSize: '0.85rem', fontWeight: 600 }}>{t.label.split(' ')[0]}</div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {theme === 'Custom' && (
                    <div className="form-group">
                      <label className="form-label">自訂插畫風格</label>
                      <input 
                        type="text" 
                        className="form-input" 
                        placeholder="例如：彩色鉛筆素描、8-bit 復古風、柔和黏土動畫風"
                        value={customStyle}
                        onChange={(e) => setCustomStyle(e.target.value)}
                      />
                    </div>
                  )}

                  <div className="form-group" style={{ marginTop: '20px' }}>
                    <h4 style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', borderBottom: '1px dashed var(--border-glass)', paddingBottom: '4px', marginBottom: '12px' }}>
                      主角設定
                    </h4>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '12px', marginTop: '8px' }}>
                      <div className="form-group">
                        <label className="form-label">名字</label>
                        <input 
                          type="text" 
                          className="form-input" 
                          value={protagonistName} 
                          onChange={(e) => setProtagonistName(e.target.value)}
                        />
                      </div>
                      <div className="form-group">
                        <label className="form-label">外觀（具體細節）</label>
                        <input 
                          type="text" 
                          className="form-input" 
                          value={protagonistDescription} 
                          onChange={(e) => setProtagonistDescription(e.target.value)}
                          placeholder="例如：戴著紅色領巾的小棕色小狗"
                        />
                      </div>
                    </div>
                  </div>

                  <div className="form-group">
                    <h4 style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', borderBottom: '1px dashed var(--border-glass)', paddingBottom: '4px', marginBottom: '12px' }}>
                      夥伴與道具（選填）
                    </h4>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '12px', marginTop: '8px' }}>
                      <div className="form-group">
                        <label className="form-label">夥伴名字</label>
                        <input 
                          type="text" 
                          className="form-input" 
                          value={companionName} 
                          onChange={(e) => setCompanionName(e.target.value)} 
                          placeholder="例如：奧利佛"
                        />
                      </div>
                      <div className="form-group">
                        <label className="form-label">夥伴外觀</label>
                        <input 
                          type="text" 
                          className="form-input" 
                          value={companionDescription} 
                          onChange={(e) => setCompanionDescription(e.target.value)}
                          placeholder="例如：有黃色眼睛的蓬鬆灰貓頭鷹"
                        />
                      </div>
                    </div>
                    
                    <div className="form-group">
                      <label className="form-label">故事線</label>
                      <input 
                        type="text" 
                        className="form-input" 
                        value={specialTool} 
                        onChange={(e) => setSpecialTool(e.target.value)}
                        placeholder="例如：靠近線索時會發光的放大鏡"
                      />
                    </div>
                  </div>
                </div>

                {/* Right Form: Settings & Model Choice */}
                <div>
                  <div className="form-group">
                    <label className="form-label">故事語氣</label>
                    <select className="form-select" value={tone} onChange={(e) => setTone(e.target.value)}>
                      <option value="Whimsical">奇幻童話感</option>
                      <option value="Epic & Adventurous">壯闊冒險</option>
                      <option value="Mysterious & Cozy">溫暖解謎</option>
                      <option value="Spooky & Thrilling">微驚悚刺激</option>
                      <option value="Heartwarming & Gentle">溫馨柔和</option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">目標年齡</label>
                    <select className="form-select" value={ageGroup} onChange={(e) => setAgeGroup(e.target.value)}>
                      <option value="3-5 years">幼兒（3-5 歲）：簡單詞彙、有節奏感</option>
                      <option value="6-8 years">初階讀者（6-8 歲）：有趣、容易投入的冒險</option>
                      <option value="9-12 years">高年級（9-12 歲）：較複雜劇情與解謎</option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">頁數</label>
                    <select className="form-select" value={pagesCount.toString()} onChange={(e) => setPagesCount(parseInt(e.target.value))}>
                      <option value="3">3 頁（迷你故事）</option>
                      <option value="5">5 頁（標準篇幅）</option>
                      <option value="8">8 頁（加長篇）</option>
                      <option value="10">10 頁（完整冒險）</option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">寫作引擎（Gemini 模型）</label>
                    <select className="form-select" value={model} onChange={(e) => setModel(e.target.value)}>
                      <option value="gemini-2.5-flash">Gemini 2.5 Flash（快速且聰明）</option>
                      <option value="gemini-2.0-flash">Gemini 2.0 Flash（穩定）</option>
                    </select>
                  </div>

                  <div className="form-group">
                    <label className="form-label">插畫風格</label>
                    <select 
                      className="form-select" 
                      value={illustrationStyle} 
                      onChange={(e) => setIllustrationStyle(e.target.value as 'fairy' | 'simple_strokes')}
                    >
                      <option value="fairy">童話 / 水彩 🎨</option>
                      <option value="simple_strokes">簡筆線條（極簡塗鴉）✏️</option>
                    </select>
                  </div>

                  <div style={{ marginTop: '40px' }}>
                    <button 
                      className="btn btn-primary" 
                      onClick={handleGenerateBook}
                      style={{ width: '100%', justifyContent: 'center', padding: '16px' }}
                      disabled={loading}
                    >
                      <Sparkles size={20} />
                      生成冒險故事書
                    </button>
                  </div>
                </div>

              </div>
            </div>

            {/* LIBRARY / PAST ADVENTURES LIST */}
            <div className="glass-panel" style={{ padding: '32px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px', marginBottom: '24px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <BookOpen size={24} style={{ color: 'var(--primary)' }} />
                  <h3 style={{ fontSize: '1.4rem', fontWeight: 600, margin: 0 }}>我的故事書庫（{library.length}）</h3>
                </div>
                
                <div style={{ display: 'flex', gap: '10px' }} className="no-print">
                  <button 
                    className="btn btn-secondary" 
                    style={{ 
                      padding: '6px 12px', 
                      fontSize: '0.85rem', 
                      display: 'flex', 
                      alignItems: 'center', 
                      gap: '6px',
                      borderColor: 'var(--primary)',
                      color: 'var(--primary)'
                    }}
                    onClick={() => {
                      syncLibrary(syncKey);
                    }}
                    title="強制重新與伺服器同步"
                    disabled={syncStatus === 'syncing'}
                  >
                    <RefreshCw size={14} className={syncStatus === 'syncing' ? 'spin' : ''} />
                    {syncStatus === 'syncing' ? '同步中...' : '同步啟用'}
                  </button>

                  <button 
                    className="btn btn-secondary" 
                    style={{ padding: '6px 12px', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '6px' }}
                    onClick={handleExportLibraryJSON}
                    title="將所有故事備份成 JSON 檔"
                  >
                    <Download size={14} />
                    匯出備份
                  </button>
                  
                  <label 
                    className="btn btn-secondary" 
                    style={{ padding: '6px 12px', fontSize: '0.85rem', display: 'flex', alignItems: 'center', gap: '6px', cursor: 'pointer' }}
                    title="從備份 JSON 檔還原故事"
                  >
                    <Plus size={14} />
                    匯入備份
                    <input 
                      type="file" 
                      accept=".json" 
                      onChange={handleImportLibraryJSON} 
                      style={{ display: 'none' }} 
                    />
                  </label>
                </div>
              </div>

              {syncError && (
                <div style={{ 
                  display: 'flex', 
                  gap: '8px', 
                  color: '#ef4444', 
                  backgroundColor: 'rgba(239, 68, 68, 0.1)', 
                  padding: '12px', 
                  borderRadius: '8px', 
                  marginBottom: '20px', 
                  fontSize: '0.85rem', 
                  lineHeight: '1.4' 
                }}>
                  <AlertCircle size={16} style={{ flexShrink: 0, marginTop: '2px' }} />
                  <span>{syncError}</span>
                </div>
              )}

              {library.length === 0 ? (
                <div style={{ textAlign: 'center', padding: '40px', color: 'var(--text-muted)' }}>
                  <HelpCircle size={48} style={{ margin: '0 auto 16px', opacity: 0.5 }} />
                  <p>書庫目前是空的。使用上方工坊生成你的第一本冒險故事吧！</p>
                </div>
              ) : (
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '20px' }}>
                  {library.map((book) => {
                    const themeObj = THEME_OPTIONS.find(t => t.id === book.config.theme);
                    // Use page 1 image as cover
                    const coverImageUrl = book.images && book.images[0]
                      ? book.images[0]
                      : `https://image.pollinations.ai/prompt/${encodeURIComponent(
                          book.pages[0].illustrationPrompt + ', ' + (
                            book.config.illustrationStyle === 'simple_strokes'
                              ? 'minimalist simple black ink outline sketch on a clean solid white background, cute childlike marker doodle style, simple strokes, black ink on white paper, no color, no background detail'
                              : (themeObj ? themeObj.promptStyle : 'children\'s book illustration')
                          )
                        )}?width=300&height=220&nologo=true&seed=${book.seeds[0]}`;

                    return (
                      <div 
                        key={book.id} 
                        className="glass-panel" 
                        style={{ display: 'flex', flexDirection: 'column', overflow: 'hidden', borderRadius: '12px', border: '1px solid var(--border-glass)' }}
                      >
                        <div style={{ height: '140px', overflow: 'hidden', position: 'relative', background: '#2d3748' }}>
                          <img src={coverImageUrl} alt={book.title} style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                          <span style={{ position: 'absolute', top: '10px', right: '10px', background: 'rgba(7, 9, 19, 0.8)', padding: '4px 8px', borderRadius: '4px', fontSize: '0.75rem', fontWeight: 600 }}>
                            {book.pages.length} 頁
                          </span>
                        </div>
                        
                        <div style={{ padding: '16px', flexGrow: 1, display: 'flex', flexDirection: 'column', justifyContent: 'space-between' }}>
                          <div>
                            <h4 style={{ fontSize: '1.1rem', fontWeight: 600, marginBottom: '6px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }} title={book.title}>
                              {book.title}
                            </h4>
                            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                              主角：<strong>{book.config.protagonistName}</strong>
                            </p>
                            <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginBottom: '12px' }}>
                              建立日期：{book.createdAt} | 主題：{THEME_OPTIONS.find(t => t.id === book.config.theme)?.label.split(' ')[0] || book.config.theme}
                            </p>
                          </div>

                          <div style={{ display: 'flex', gap: '8px', borderTop: '1px solid var(--border-glass)', paddingTop: '12px' }}>
                            <button 
                              className="btn btn-secondary" 
                              style={{ padding: '6px 12px', fontSize: '0.8rem', flexGrow: 1, justifyContent: 'center' }}
                              onClick={() => {
                                setCurrentBook(book);
                                setCurrentPageIndex(0);
                              }}
                            >
                              開啟故事書
                            </button>
                            <button 
                              className="btn btn-secondary" 
                              style={{ padding: '8px', color: '#ef4444', borderColor: 'rgba(239, 68, 68, 0.2)' }}
                              onClick={() => setBookToDelete(book)}
                              title="刪除故事書"
                            >
                              <Trash2 size={14} />
                            </button>
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

          </div>
        )}
      </main>

      {/* GEMINI API KEY MODAL DIALOG */}
      {showKeyModal && (
        <div className="modal-overlay no-print">
          <div className="glass-panel modal-content">
            <h3 style={{ fontSize: '1.3rem', fontWeight: 600, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Key style={{ color: 'var(--primary)' }} />
              需要 Gemini API Key
            </h3>
            
            <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '20px' }}>
              為了撰寫故事與描述，這個應用會直接連線到 Google Gemini 官方 API。
              你的 Key 只會儲存在本機瀏覽器，不會上傳到其他地方。
            </p>

            <div className="form-group" style={{ marginBottom: '24px' }}>
              <label className="form-label">輸入 Gemini API Key</label>
              <input 
                type="password" 
                className="form-input" 
                placeholder="AIzaSy..." 
                value={tempKey}
                onChange={(e) => setTempKey(e.target.value)}
              />
              <small style={{ color: 'var(--text-muted)', display: 'block', marginTop: '4px' }}>
                還沒有 Key？可以到 <a href="https://ai.google.dev/" target="_blank" rel="noreferrer" style={{ color: 'var(--primary)' }}>ai.google.dev</a> 免費取得。
              </small>
            </div>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
              {(apiKey || serverHasKey) && (
                <button className="btn btn-secondary" onClick={() => setShowKeyModal(false)}>
                  取消
                </button>
              )}
              <button 
                className="btn btn-primary" 
                onClick={() => handleSaveKey(tempKey)}
                disabled={!tempKey.trim()}
              >
                儲存並繼續
              </button>
            </div>
          </div>
        </div>
      )}

      {/* DELETE CONFIRMATION MODAL */}
      {bookToDelete && (
        <div className="modal-overlay no-print">
          <div className="glass-panel modal-content" style={{ maxWidth: '400px' }}>
            <h3 style={{ fontSize: '1.3rem', fontWeight: 600, marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px', color: '#ef4444' }}>
              <Trash2 style={{ color: '#ef4444' }} />
              刪除冒險故事？
            </h3>
            
            <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '24px', lineHeight: '1.5' }}>
              確定要永久刪除 <strong>「{bookToDelete.title}」</strong> 嗎？這個動作無法復原。
            </p>

            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px' }}>
              <button 
                className="btn btn-secondary" 
                onClick={() => setBookToDelete(null)}
              >
                取消
              </button>
              <button 
                className="btn btn-primary" 
                style={{ backgroundColor: '#ef4444', borderColor: '#ef4444', color: '#ffffff' }}
                onClick={() => {
                  handleDeleteBook(bookToDelete.id);
                  setBookToDelete(null);
                }}
              >
                刪除
              </button>
            </div>
          </div>
        </div>
      )}


    </div>
  );
}
